apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: gitops-demo-cluster
  namespace: argocd
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: pacific-gold-storage-policy
    workers:
      count: 2
      class: best-effort-xsmall
      storageClass: pacific-gold-storage-policy
  distribution:
    version: v1.16
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
